apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {{- include "chartLabels" . | nindent 4 }}
    app: {{ include "appName" . }}
  name: {{ include "appName" . }}
  namespace: default
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "appName" . }}
  template:
    metadata:
      labels:
        app: {{ include "appName" . }}
    spec:
      {{- if .Values.volumes }}
      volumes: {{- include "volumes" . | indent 8 }}
      {{- end }}
      containers:
        - name: {{ include "appName" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy}}
          ports:
            - containerPort: {{ .Values.application.targetPort }}
          env:
            - name: TZ
              value: Europe/Moscow
            - name: LANG
              value: ru_RU.UTF-8
          {{- if or .Values.envVars.app.config .Values.envVars.app.secret }}
          envFrom:
          {{- if .Values.envVars.app.config }}
            - configMapRef:
                name: {{ tpl .Values.envVars.app.config . }}
          {{- end }}
          {{- if .Values.envVars.app.secret }}
            - secretRef:
                name: {{ tpl .Values.envVars.app.secret . }}
          {{- end }}
          {{- end }}
