apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}
  labels:
    run: {{ .Values.application.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.application.name }}
  ports:
    - nodePort: {{ .Values.application.nodePort }}
      port: {{ .Values.application.port }}
      targetPort: {{ .Values.application.targetPort }}
      protocol: TCP
