replicaCount: 1

image:
  registry: docker.io
  repository: jalona/notification-route
  tag: 1.0.0
  pullPolicy: Always

application:
  name: notification-route
  port: 8090
  nodePort: 30080
  targetPort: 8080
