replicaCount: 1

image:
  registry: docker.io
  repository: jalona/notification-route
  tag: 1.0.0
  pullPolicy: Always

application:
  name: notification-route
  port: 8090
  nodePort: 30080
  targetPort: 8080

volumes:
  app:
    type: config

envVars:
  app:
    config: "{{ .Chart.Name }}-config"
    secret: "{{ .Chart.Name }}-secret"

appConfigData:
  LOGGING_LEVEL_ROOT: 'INFO'

appSecretData:
  AWS_SQS_ACCESS_KEY: ''
  AWS_SQS_SECRET_KEY: ''
