apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl .Values.envVars.app.secret . }}
  labels:
    app: {{ tpl .Values.envVars.app.secret . }}
type: Opaque
stringData: {{ toYaml .Values.appSecretData | nindent 2 }}
