replicaCount: 1

image:
  registry: docker.io
  repository: jalona/notification-sms-adapter
  tag: 1.0.0
  pullPolicy: Always

application:
  name: notification-sms-adapter
  port: 8092
  nodePort: 30082
  targetPort: 8082

volumes:
  app:
    type: config

envVars:
  app:
    config: "{{ .Chart.Name }}-config"
    secret: "{{ .Chart.Name }}-secret"

appConfigData:
  LOGGING_LEVEL_ROOT: 'INFO'

appSecretData:
  AWS_SQS_ACCESS_KEY: ''
  AWS_SQS_SECRET_KEY: ''
