replicaCount: 1

image:
  registry: docker.io
  repository: jalona/notification-sms-adapter
  tag: 1.0.0
  pullPolicy: Always

application:
  name: notification-sms-adapter
  port: 8092
  nodePort: 30082
  targetPort: 8082
